### ISSUE TITLE
Add support for class template

### ISSUE THREAD

**Issue by sdebionne** [boostorg/describe#17]
Would support for class template description be implementable (eventually with a different macro)?

```cpp
namespace app {
    template <typename T>
    struct point
    {
        T x;
        T y;
    };

    BOOST_DESCRIBE_STRUCT(point, (), (x, y))      // Not supported
    BOOST_DESCRIBE_STRUCT(point<int>, (), (x, y)) // OK
} //namespace app
```

**Comment by pdimov** [comment]
Class templates already work with BOOST_DESCRIBE_CLASS. (But MSVC can't compile it due to compiler bugs.)

**Comment by sdebionne** [comment]
Awesome, I was unlucky then. Just to be sure, `BOOST_DESCRIBE_CLASS` works with class templates but not `BOOST_DESCRIBE_STRUCT` or am I reading too much between the lines? It's just that `BOOST_DESCRIBE_CLASS` is slightly more intrusive, being defined inside the class...

**Comment by pdimov** [comment]
That's correct, BOOST_DESCRIBE_CLASS works, BOOST_DESCRIBE_STRUCT doesn't (work for templates).

However I notice I don't actually have a test for it. I probably intended to add one and got distracted with other things.

**Comment by pdimov** [comment]
Oh it works with VS 16.10. Cool.

**Comment by sdebionne** [comment]
Thanks for clarifying. Making `BOOST_DESCRIBE_STRUCT` work for templates, would that be possible? If not, I'll just close the issue.

**Comment by pdimov** [comment]
No, it can't work as is. It might be possible to have another macro `BOOST_DESCRIBE_TEMPLATE_STRUCT` but the syntax in the general case will be awful, I think.

**Comment by pdimov** [comment]
It turns out it only works with VS2019 with /std:c++latest. :-)

**Comment by pdimov** [comment]
https://github.com/boostorg/describe/commit/7e9f1f0eb9759a0b75f0ba8097764c9146c0cf49
